/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: questions.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./questions_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.QuestionServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.QuestionServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SearchByTitleRequest,
 *   !proto.SearchByTitleResponse>}
 */
const methodDescriptor_QuestionService_SearchByTitle = new grpc.web.MethodDescriptor(
  '/QuestionService/SearchByTitle',
  grpc.web.MethodType.UNARY,
  proto.SearchByTitleRequest,
  proto.SearchByTitleResponse,
  /**
   * @param {!proto.SearchByTitleRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.SearchByTitleResponse.deserializeBinary
);


/**
 * @param {!proto.SearchByTitleRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SearchByTitleResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SearchByTitleResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.QuestionServiceClient.prototype.searchByTitle =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/QuestionService/SearchByTitle',
      request,
      metadata || {},
      methodDescriptor_QuestionService_SearchByTitle,
      callback);
};


/**
 * @param {!proto.SearchByTitleRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SearchByTitleResponse>}
 *     Promise that resolves to the response
 */
proto.QuestionServicePromiseClient.prototype.searchByTitle =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/QuestionService/SearchByTitle',
      request,
      metadata || {},
      methodDescriptor_QuestionService_SearchByTitle);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.GetByIdRequest,
 *   !proto.Question>}
 */
const methodDescriptor_QuestionService_GetById = new grpc.web.MethodDescriptor(
  '/QuestionService/GetById',
  grpc.web.MethodType.UNARY,
  proto.GetByIdRequest,
  proto.Question,
  /**
   * @param {!proto.GetByIdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Question.deserializeBinary
);


/**
 * @param {!proto.GetByIdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Question)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Question>|undefined}
 *     The XHR Node Readable Stream
 */
proto.QuestionServiceClient.prototype.getById =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/QuestionService/GetById',
      request,
      metadata || {},
      methodDescriptor_QuestionService_GetById,
      callback);
};


/**
 * @param {!proto.GetByIdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Question>}
 *     Promise that resolves to the response
 */
proto.QuestionServicePromiseClient.prototype.getById =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/QuestionService/GetById',
      request,
      metadata || {},
      methodDescriptor_QuestionService_GetById);
};


module.exports = proto;

